database:
    tables:
        coupons_export_queue:
            pico_email_mailinator: [email]
        db:
            pico_hash: [User]
        deletion_authorization:
            pico_email_mailinator: [mail]
        user:
            pico_hash: [User]
        users:
            pico_hash: [username]
            pico_email_mailinator: [email]