database:
    tables:
#        icoupons_export_queue:
#            pico_email_mailinator: [email]
#        deletion_authorization:
#            pico_email_mailinator: [mail]
#        users:
#            pico_hash: [username]
#            pico_email_mailinator: [email]